name: T-Display-Pico C3

permissions:
  contents: write

on:
  push:
    tags:
     - 'v*'
  schedule:
     - cron: '0 0 * * 0'  # Se ejecutará a las 00:00 UTC cada domingo
  
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - name: Clone Micropython
      run: git clone --recurse-submodules https://github.com/micropython/micropython.git

    - name: Clone st7789_mpy
      run: git clone https://github.com/russhughes/st7789_mpy.git

    - name: Copy tdt_config and some fonts like frozen modules
      run: |
       ls -R $GITHUB_WORKSPACE/st7789_mpy/
       cp "$GITHUB_WORKSPACE/st7789_mpy/examples/configs/t-picoc3/tft_config.py" "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp "$GITHUB_WORKSPACE/st7789_mpy/examples/configs/tdisplay_rp2040/tft_buttons.py" "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp $GITHUB_WORKSPACE/st7789_mpy/examples/chango/chango.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp $GITHUB_WORKSPACE/st7789_mpy/examples/chango/chango_16.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp $GITHUB_WORKSPACE/st7789_mpy/examples/chango/chango_32.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp $GITHUB_WORKSPACE/st7789_mpy/examples/chango/chango_64.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp $GITHUB_WORKSPACE/st7789_mpy/fonts/vector/*.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp $GITHUB_WORKSPACE/st7789_mpy/fonts/truetype/*.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       cp $GITHUB_WORKSPACE/st7789_mpy/fonts/bitmap/*.py "$GITHUB_WORKSPACE/micropython/ports/rp2/modules/"
       
    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y gcc-arm-none-eabi libssl-dev python3 python3-pip python3-venv build-essential libffi-dev git pkg-config

    - name: Build MicroPython for RP2040
      run: |
        cd micropython
        make -C mpy-cross
        cd ports/rp2
        make USER_C_MODULES=$GITHUB_WORKSPACE/st7789_mpy/st7789/micropython.cmake
        make submodules
        make

    - name: Move .uf2 files to artifacts
      run: |
        mkdir -p ./artifacts
        cp micropython/ports/rp2/build-RPI_PICO/*.uf2 ./artifacts/RP2040.uf2

    - name: Release Changelog Builder
      uses: mikepenz/release-changelog-builder-action@v5
      id: changelog
      with:
        config: '.github/changelog-config.yml'
            
    - name: Generate Release Notes
      id: release_notes
      run: |
        echo "## Weekly Automated Release" >> $GITHUB_WORKSPACE/release_notes.md
        echo "This is an automated release that includes the latest updates from the Micropython and st7789_mpy repositories." >> $GITHUB_WORKSPACE/release_notes.md
        echo "" >> $GITHUB_WORKSPACE/release_notes.md
        echo "## How to flash the firmware" >> release_notes.md
        echo "### Windows or Linux:" >> release_notes.md
        echo "1. Download the .uf2 file from the release." >> release_notes.md
        echo "2. Press and hold the BOOTSEL button on the RP2040 and connect it to your computer via USB." >> release_notes.md
        echo "3. Release the button. The RP2040 will appear as a removable drive." >> release_notes.md
        echo "4. Drag and drop the .uf2 file onto the drive." >> release_notes.md
        echo "5. The RP2040 will reboot and run MicroPython." >> release_notes.md
        echo "" >> release_notes.md
        echo "## Examples usage" >> release_notes.md
        echo "Please use the examples located in the [examples folder of the st7789_mpy repository](https://github.com/russhughes/st7789_mpy/tree/master/examples)." >> release_notes.md
        
    - name: Generate Tag
      id: tag
      run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ env.TAG_NAME }} 
        title: "MicroPython + ST7789 Display Driver Release for version ${{ env.TAG_NAME }}"
        body: |
          ## Release Version: ${{ env.TAG_NAME }}

          ### Changelog
          ${{ steps.changelog.outputs.changelog }}

          ## How to Flash the Firmware
          ### Windows:
          1. Download the .uf2 file from the release.
          2. Press and hold the BOOTSEL button on the RP2040 and connect it to your computer via USB.
          3. Release the button. The RP2040 will appear as a removable drive.
          4. Drag and drop the .uf2 file onto the drive.
          5. The RP2040 will reboot and run MicroPython.

          ## Examples Usage
          Please use the examples located in the [examples folder of the st7789_mpy repository](https://github.com/russhughes/st7789_mpy/tree/master/examples).

          files: ./artifacts/*
          
